Jekyll站点CI

触发:
推送:
分支: [ "main" ]
拉取请求:
分支: [ "main" ]

作业:
构建:

运行于: ubuntu-latest

步骤:
    - 使用: actions/checkout@v4
    - 名称: 在jekyll/builder容器中构建站点
运行: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
